### ISSUE TITLE
Use of LIXA with PostgreSQL preprocessors

### ISSUE THREAD

**Issue by GitMensch** [tiian/lixa#10] opened 2021-12-22 16:35 UTC
The sample shows a direct CALL to the psql interface and mentions that the CALLs should not be used to create the connection.
How to use this with SQL precompilers like [Gix-SQL](https://github.com/mridoni/gix/blob/main/doc/gixsql.md) or its origin [open-cobol-esql](https://github.com/opensourcecobol/Open-COBOL-ESQL/) or [esqlOC](https://sourceforge.net/p/gnucobol/contrib/HEAD/tree/trunk/esql/)?
Do we need to adjust their code to use LIXA?

**Comment by tiian** [comment] 2021-12-23 18:36
Hi!
The question deserves a quite long answer because you have spotted one of the most complex topics related to the design of LIXA and the constraints put in place by the TX standard and some client libraries like libpq.

I'll try to make a long story (quite) short.

For the sake of easiness, imagine to develop an Application Program that uses a single XA Resource Manager and the TX Transaction Demarcation as the API to coordinate the transaction.
The example is trivial, I know, you don't need XA with a single Resource Manager, but for the following explanation even a single XA Resource Manager shows where the issue is. You can extend the reasoning to two or more XA Resource Managers in a straightforward way.

**TX standard does not work with handlers**: when you call "tx_open" (TXOPEN) you get a return code, but you don't get a connection handler.
At the same time when you call "tx_open()" (TXOPEN) you can't pass a connection handler.
Looking at "tx_open()" definition you read:
_

> The function tx_open( ) opens a set of resource managers in a portable manner. It invokes a transaction manager to read information specific to the resource manager in a manner specific to the transaction manager and pass this information to the resource managers linked to the caller.

_

Who designed XA and TX decided to delegate the opening of the Resource Managers to the Transaction Manager and not to the Application Program itself.
In practice, when your Application Program calls "tx_open()" (TXOPEN), the LIXA library, under the covers, opens the Resource Manager(s) behalf of your Application Program and stores the connection handler(s) in the thread context (if you don't use POSIX threads it doesn't matter, it stores the connection handler(s) in the process context).

Coming back to your original question, I suppose you are referring to this code snippet:


      * Retrieve PostgreSQL connection
      * do NOT use standard PostgreSQL functions because they don't
      * return an XA connection, but a transaction manager independent
      * connection
      *
            CALL "LIXAPQGETCONN" RETURNING PGCONN.

[LIXAPQGETCONN](https://github.com/tiian/lixa/blob/master/src/client/switch/postgresql/liblixapq.c) is not part of the TX standard, but it's an "hack" to retrieve the PostgreSQL connection that has been created by the LIXA library behalf of your Application Program: it's the same connection that the LIXA library uses to commit, rollback and retrieve the state of a transaction when the Application Program calls "tx_commit()" (TXCOMMIT) and "tx_rollback()" (TXROLLBACK).

Of course there are alternatives that can be implemented to overcome the limitation. The one I implemented is with XTA: XA Transaction API.
XTA implements the concept of "resource enlisting" and you can pass your own connection handler to it, here is an [example for C](https://github.com/tiian/lixa/blob/master/doc/examples/xta/example_xta_sa01.c); unfortunately XTA is not currently available for COBOL, but an expert COBOL/C developer could wrap the XTA C library to create an equivalent XTA COBOL library.

The same limitation applies to MySQL, but not to Oracle DB, for example, because the XA connection handler associated to a POSIX thread can be retrieved with [dedicated functions](https://github.com/tiian/lixa/blob/master/doc/examples/example2_ora.c) provided by its client library; the same applies to [DB2](https://github.com/tiian/lixa/blob/master/doc/examples/example3_db2.c) even if it's long time I don't play with it.

I hope the above explanation helps, please come back with additional questions if something is not clear.

**Comment by GitMensch** [comment] 2021-12-23 19:12
Thanks  for the explanation, that helps a lot to understand the issue.

So as I see it a preprocessor library that normally would do the connection could at least be adjusted to keep it and return it to lixa, correct? Could you add a documentation / layout how those callback functions should be written (ideally matching db2/oci)?

Other than that lixa could add stuff like LIXAODBCGETCONN - but that would only be reasonable if lixa would create the connections itself, so the "if you have a callback function that abides to this API" approach would be more reasonable for example esqlOC correct?

**Comment by tiian** [comment] 2021-12-24 15:10
Let me suggest to go on the discussion using a real life use case and a sample code snippet.
In the past "abstract reasoning" on this topic didn't pay off me.
One of the tricky point about Embedded SQL is "how many and what type of databases are interfaced by Embedded SQL"?
If the use case is related to a single relational database, the integration between an Application Program with ESQL statements and LIXA might be reasonable straightforward, basically just a "technical integration".
If the use case is related to two databases, several questions rise:

- is the Application Program interfacing two databases of the same technology, like for example synchronous update of two different PostgreSQL databases?
- is the Application Program interfacing two databases of different technology, like for example updating a PostgreSQL and an Oracle DB databases? (Typical use case related to migration scenarios).

Both the above use cases create some pains due to the architecture dictated by XA and TX standards.
I think it's more appropriate to describe the interesting use case (number and type of XA Resource Managers) and look at a sample source code: with that in place it would be easier for me to figure out a good implementation solution.

**Comment by tiian** [comment] 2022-01-15 20:32
Is there something else to discuss on this topic? Otherwise I'll prefer to close it.

**Comment by GitMensch** [comment] 2022-01-15 21:46
> If the use case is related to a single relational database, the integration between an Application Program with ESQL statements and LIXA might be reasonable straightforward, basically just a "technical integration".

That's the scenario (or two but in this case one is read-only).

How would this "technical integration" look like?

**Comment by tiian** [comment] 2022-01-19 20:43
Look at [example5_pql.c](https://github.com/tiian/lixa/blob/master/doc/examples/example5_pql.c) as an example:
PostgreSQL connection, a PGconn* , is retrieved by mean on calling 

    PGconn *lixa_pq_get_conn();

instead of the default 

    PGconn *PQconnectdb(const char *conninfo);

because the connection with the resource manager is created when tx_open() is called.

The easiest way to integrate Embedded SQL for PostgreSQL, if the source code of the ESQL pre-processor can be changed, would be:

1. adding an additional flag to the ESQL pre-processor sounding like "--lixa-tx" or whatever you prefer
2. changing the code generated by the ESQL pre-processor replacing "PGconnectdb" with "lixa_pq_get_conn"

The above applies to C.
Talking about COBOL I don't know how the ESQL pre-processor for COBOL works: 
1. supposing it translates from COBOL+ESQL to pure COBOL, you need to wrap "lixa_pq_get_conn" to make it COBOL like; then the COBOL to C translator will do the rest of the job
2. supposing it translates from COBOL+ESQL directly to C, you just need to replace PGconnectdb() with lixa_pg_get_conn() as explained above

Hope it helps.

**Closed as completed** 2022-12-10 11:21 UTC
Labels: question

**Comment by GitMensch** [comment] 2022-12-10 12:15
@mridoni While an issue is likely more useful in the GixSQL repo - please have a look at this information and check for a possible integratio on GNU/Linux when using PG, MySQL/MariaDB, and _possibly_ Oracle [I _think_ that may ony be  possible with OCI?] (@tiian if there are more DBs that could be used please drop the note).

**Comment by tiian** [comment] 2022-12-10 14:43
As far as TX Transaction Demarcation Specification is used, LIXA has been positively tested with 5 different Resource Managers: Oracle DB, IBM DB2, PostgreSQL, MySQL/MariaDB, IBM MQ. Only PostgreSQL and MySQL/MariaDB need the hack explained above because they do not provide a standard XA interface, but just a "quite equivalent" one.
