### ISSUE TITLE
xta_start after xta_recover causes lixad to exit

### ISSUE THREAD

**Issue by LWilkinson-LzLabs** [tiian/lixa#6] opened 2020-09-23 12:08 UTC
Our client program makes the following sequence of calls

> xta_transaction_manager_new()
> xta_native_xa_resource_new(()
> xta_native_xa_resource_new()
> xta_transaction_manager_create_transaction()
> xta_transaction_enlist_resource()
> xta_transaction_enlist_resource()
> xta_transaction_recover()
> xta_transaction_safe_delete() (No actual delete, just a check)
> xta_transaction_start()

During the xta_transaction_start() call lixad exits with the following trace lines:
> 13:12:02.198698 [3891/140247507519232] lixa_msg_retrieve
> 13:12:02.198704 [3891/140247507519232] lixa_msg_retrieve: poll returned 0x1 for fd 14
> 13:12:02.198712 [3891/140247507519232] lixa_msg_retrieve: XML message prefix is '000367' (367)
> 13:12:02.198719 [3891/140247507519232] lixa_msg_retrieve: fd=14 returned 367 bytes
> 13:12:02.198724 [3891/140247507519232] lixa_msg_retrieve/excp=10/ret_cod=0/errno=0
> 13:12:02.198729 [3891/140247507519232] server_manager_msg_proc
> 13:12:02.198734 [3891/140247507519232] server_fsm_message_arrived
> 13:12:02.198738 [3891/140247507519232] server_fsm_message_arrived: sessid='7548f2c', old state=4 ('MESSAGE_ARRIVED')
> 13:12:02.198743 [3891/140247507519232] server_fsm_message_arrived: sessid='7548f2c', this state transition is not allowed
> 13:12:02.198748 [3891/140247507519232] server_fsm_message_arrived/excp=0/ret_cod=-31/errno=0

Full traces of client and lixad are attached:
[Client_recovery_crash.txt](https://github.com/tiian/lixa/files/5267984/Client_recovery_crash.txt)
[Lixad_recovery_crash.txt](https://github.com/tiian/lixa/files/5267986/Lixad_recovery_crash.txt)

**Comment by tiian** [comment] 2020-09-23 21:06
Some comments about the use case.
Method "xta_transaction_safe_delete()" must be considered an internal ("private") method and it's not designed to be used by Application Programs. It's not available in C++ and Java; in theory you should never necessitate it, it's used by xta_transaction_manager to avoid an orphan pointer. I marked it as DEPRECATED in commit cfd5e2843fdb98c066a1c6667f7c605b6739ad99.

xta_transaction_recover can be used as in [https://github.com/tiian/lixa/blob/master/tests/src/case0104.c#L472](https://github.com/tiian/lixa/blob/master/tests/src/case0104.c#L472) it should work even in your use case.

I don't like the lixad closes with a protocol violation and I deserve to reproduce the scenario and to prevent lixad shutdown. 
My first analysis: use case never tested.

Specifying explicit xta_transaction_recover is normally not required because xta_transaction_start does it automatically; if you do need explicit transaction recovery, try to follow the example cited above or use xta_transaction_start / xta_transaction_rollback.

I'm not sure re-using the same transaction after xta_transaction_recover is easy to implement because XTA must take care of some non obvious underlying constraints. I would consider it an enhancement, but I have to be sure it provides real value before starting that type of development.

Hoping the above helps.

**Comment by tiian** [comment] 2020-09-25 21:43
Commit 29824f164238ef878708ccef577c065688f641bf contains a first patch: LIXA state server does not close down. This does not close the issue because something better can be done at the client side too.

**Comment by tiian** [comment] 2020-09-26 19:29
It seems your use case can be supported with a minor change as in commit f13c31abddd4b3aa45b5b2d9d8e7c9def75e04ef.

The attached example seems to work as expected:

[example_xta_sa02.c.gz](https://github.com/tiian/lixa/files/5287214/example_xta_sa02.c.gz)

it can be build with the same command of doc/examples/xta/example_xta_sa01.c

please give it a try.

**Comment by tiian** [comment] 2020-10-03 17:27
The bug should be fixed.
Examples about the test case are case0111.c and case0112.c in tests/src directory.
if xta_transaction_recover is called more than one time, starting from the first repetition it ends with a warning like below:

2020-10-03 18:58:53.807156 [17242/46958062156224] xta_transaction_recover
2020-10-03 18:58:53.807159 [17242/46958062156224] xta_transaction_recover: to start automatic recovery, client status should be 0, but the current value is 1, bypassing...
2020-10-03 18:58:53.807161 [17242/46958062156224] xta_transaction_recover/excp=1/ret_cod=3/errno=0
2020-10-03 18:58:53.807163 [17242/46958062156224] { "type": "StackTrace", "date": "2020-10-03", "time": "18:58:53.807163", "process_id": 17242, "thread_id": 46958062156224, "function_name": xta_transaction_recover", "source_file_name": "xta_transaction.c", "source_file_line": "766", "exception": 1, "return_code": 3, "return_code_text": "WARNING: operation was not performed because it can not be requested", "errno": 0, "errno_text": "Success", "trace_module": 0x20 }

Only before the first "start", an automatic recover can be forced.

**Closed as completed by tiian** 2020-10-03 17:27 UTC
Labels: bug, enhancement
